### ISSUE TITLE
unable to select selection

### ISSUE THREAD

**Issue by ipk1** [netevert/delator#2]
when i run delator -p and once the logs are populated i am asked to select however anything i put is invalid.

Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:11
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:all
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:all
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:24
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:5
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:6
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:7
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:8
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:9
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:10
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:11
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:12
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:13
answer is invalid
Select log (default 'ct.googleapis.com/pilot/') [all | 0-40]:

can i select all the logs to use?

thanks

**Comment by edoardogerosa** [comment]
Hi @ipk1 , thanks for your comment - could you elaborate on the platform you are running delator on? I tried replicating the behavior on Windows with no success. If you are running it on Windows, i'd kindly ask you to provide a little more details in order for me to reproduce the issue. Thanks!

**Comment by ipk1** [comment]
@netevert i am running on linux Linux vmi342284.contaboserver.net 5.4.0-kali4-amd64 #1 SMP Debian 5.4.19-1kali1 (2020-02-17) x86_64 GNU/Linux
 thanks

**Comment by edoardogerosa** [comment]
@ipk1 i've decided to drop support for Linux. I appreciate this might cause some inconvenience to you; however, I don't have the time nor set-up to test across multiple formats 😞. Feel free to fork the project and build a Linux flavour if you wish.
